// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zarigqmtaexgcayzfqpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphcmlncW10YWV4Z2NheXpmcXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDE5MjksImV4cCI6MjA3Mzc3NzkyOX0.DzVBhVGco5ERcUEjMD909jCVrXbaTJzUfLzYfdXjQwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});